In [2]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 MB 846.3 kB/s eta 0:00:0000:0100:03


In [13]:
import torch
import numpy as np


In [14]:
tensor_from_list = torch.tensor([1, 2, 3])
print("Tensor from list:", tensor_from_list)

Tensor from list: tensor([1, 2, 3])


In [15]:
np_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = torch.from_numpy(np_array)
print("Tensor from NumPy array:\n", tensor_from_numpy)

Tensor from NumPy array:
 tensor([[1, 2],
        [3, 4]])


In [16]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

addition = a + b
print("Addition Result:", addition)

multiplication = a * a
print("Multiplication Result:", multiplication)


Addition Result: tensor([2, 4, 6])
Multiplication Result: tensor([1, 4, 9])


In [17]:
print("Tensor:", a)
print("Tensor Shape:", a.shape)
print("Tensor Data Type:", a.dtype)


Tensor: tensor([1, 2, 3])
Tensor Shape: torch.Size([3])
Tensor Data Type: torch.int64


In [18]:
A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

AxB = torch.mm(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A x B:\n", AxB)


Matrix A:
 tensor([[1, 2],
        [3, 4]])
Matrix B:
 tensor([[5, 6],
        [7, 8]])
A x B:
 tensor([[19, 22],
        [43, 50]])


In [19]:
x = torch.tensor([1, 3, 5])
y = torch.tensor([2, 4, 6])

dot_product = torch.dot(x, y)
print("Dot Product Output =", dot_product)


Dot Product Output = tensor(44)


In [20]:
T = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print("Tensor T:\n", T)

print("T[0][1]:", T[0][1])

print("First row:", T[0])

print("Second column:", T[:, 1])


Tensor T:
 tensor([[10, 20, 30],
        [40, 50, 60]])
T[0][1]: tensor(20)
First row: tensor([10, 20, 30])
Second column: tensor([20, 50])


In [21]:
print("torch.empty():\n", torch.empty(2, 3))

print("torch.zeros():\n", torch.zeros(2, 3))

print("torch.rand():\n", torch.rand(2, 3))

print("torch.ones():\n", torch.ones(2, 3))

print("torch.eye():\n", torch.eye(3))

print("torch.arange():", torch.arange(0, 10, 2))

print("torch.linspace():", torch.linspace(0, 1, steps=5))

x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
print("torch.add():", torch.add(x, y))

print("torch.mm():\n", torch.mm(A, B))

print("torch.dot():", torch.dot(x, y))

batch1 = torch.rand(2, 3, 4)
batch2 = torch.rand(2, 4, 5)
print("torch.bmm(): shape", torch.bmm(batch1, batch2).shape)

print("torch.abs():", torch.abs(torch.tensor([-3, -1, 2])))

print("torch.argmax():", torch.argmax(torch.tensor([10, 50, 20])))

print("torch.argmin():", torch.argmin(torch.tensor([10, 50, 20])))

print("torch.mean():", torch.mean(torch.tensor([1.0, 2.0, 3.0])))

print("torch.sort():", torch.sort(torch.tensor([4, 1, 3, 2])))

print("torch.cat():", torch.cat((torch.tensor([1, 2]), torch.tensor([3, 4]))))


torch.empty():
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.zeros():
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.rand():
 tensor([[0.2951, 0.9646, 0.5378],
        [0.4994, 0.4536, 0.5040]])
torch.ones():
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.eye():
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.arange(): tensor([0, 2, 4, 6, 8])
torch.linspace(): tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
torch.add(): tensor([4, 6])
torch.mm():
 tensor([[19, 22],
        [43, 50]])
torch.dot(): tensor(11)
torch.bmm(): shape torch.Size([2, 3, 5])
torch.abs(): tensor([3, 1, 2])
torch.argmax(): tensor(1)
torch.argmin(): tensor(0)
torch.mean(): tensor(2.)
torch.sort(): torch.return_types.sort(
values=tensor([1, 2, 3, 4]),
indices=tensor([1, 3, 2, 0]))
torch.cat(): tensor([1, 2, 3, 4])


In [22]:
import torch.nn as nn

model = nn.Linear(in_features=1, out_features=1)

x = torch.tensor([[1.0], [2.0], [3.0]])

y_pred = model(x)

print("Input:\n", x)
print("Predicted Output:\n", y_pred)


Input:
 tensor([[1.],
        [2.],
        [3.]])
Predicted Output:
 tensor([[ 0.3648],
        [ 0.1088],
        [-0.1473]], grad_fn=<AddmmBackward0>)
