# Assignment 1

In [1]:
!pip install kagglehub

In [2]:
import kagglehub

dataset_path = kagglehub.dataset_download("jacksondivakarr/sample34")
print(f"Dataset downloaded to: {dataset_path}")

Dataset downloaded to: /Users/priyakeshri/.cache/kagglehub/datasets/jacksondivakarr/sample34/versions/1


In [3]:
import os

print(os.listdir(dataset_path))

['processes2.csv']


In [4]:
import pandas as pd
import os

# List files in the downloaded dataset directory
downloaded_files = os.listdir(dataset_path)
print(f"Files found in the dataset directory: {downloaded_files}")

# Try to find a CSV file. Assuming there's only one relevant CSV file in the directory.
csv_file_name = None
for file in downloaded_files:
    if file.endswith('.csv'):
        csv_file_name = file
        break

if csv_file_name:
    csv_file_path = os.path.join(dataset_path, csv_file_name)
    print(f"Found CSV file: {csv_file_name}. Loading data from: {csv_file_path}")
    df = pd.read_csv(csv_file_path)

    # Display the first few rows of the DataFrame to verify
    print("Dataset loaded successfully. Displaying the first 5 rows:")
    print(df.head().to_markdown(index=False))
else:
    print("Error: No CSV file was found in the downloaded dataset directory.")
    df = None # Ensure df is defined even if no CSV is found

Files found in the dataset directory: ['processes2.csv']
Found CSV file: processes2.csv. Loading data from: /Users/priyakeshri/.cache/kagglehub/datasets/jacksondivakarr/sample34/versions/1/processes2.csv
Dataset loaded successfully. Displaying the first 5 rows:
|   Unnamed: 0 | name    |   year |   selling_price |   km_driven | fuel   | seller_type   | transmission   | owner       |   seats |   max_power (in bph) | Mileage Unit   |   Mileage |   Engine (CC) |
|-------------:|:--------|-------:|----------------:|------------:|:-------|:--------------|:---------------|:------------|--------:|---------------------:|:---------------|----------:|--------------:|
|            0 | Maruti  |   2014 |          450000 |      145500 | Diesel | Individual    | Manual         | First Owner |       5 |                74    | kmpl           |     23.4  |          1248 |
|            2 | Hyundai |   2010 |          225000 |      127000 | Diesel | Individual    | Manual         | First Owner |       5 

In [5]:
print("First 5 rows of the DataFrame:")
print(df.head().to_markdown(index=False))

print("\nValue counts for 'fuel' column:")
print(df['fuel'].value_counts().to_markdown(numalign="left", stralign="left"))

print("\nValue counts for 'owner' column:")
print(df['owner'].value_counts().to_markdown(numalign="left", stralign="left"))

print("\nValue counts for 'name' column:")
print(df['name'].value_counts().to_markdown(numalign="left", stralign="left"))

First 5 rows of the DataFrame:
|   Unnamed: 0 | name    |   year |   selling_price |   km_driven | fuel   | seller_type   | transmission   | owner       |   seats |   max_power (in bph) | Mileage Unit   |   Mileage |   Engine (CC) |
|-------------:|:--------|-------:|----------------:|------------:|:-------|:--------------|:---------------|:------------|--------:|---------------------:|:---------------|----------:|--------------:|
|            0 | Maruti  |   2014 |          450000 |      145500 | Diesel | Individual    | Manual         | First Owner |       5 |                74    | kmpl           |     23.4  |          1248 |
|            2 | Hyundai |   2010 |          225000 |      127000 | Diesel | Individual    | Manual         | First Owner |       5 |                90    | kmpl           |     23    |          1396 |
|            4 | Hyundai |   2017 |          440000 |       45000 | Petrol | Individual    | Manual         | First Owner |       5 |                81.86 | kmpl

In [6]:
df_encoded_standard = pd.get_dummies(df[['fuel', 'owner']])
print("First 5 rows of the one-hot encoded DataFrame (df_encoded_standard):")
print(df_encoded_standard.head().to_markdown(index=False))

First 5 rows of the one-hot encoded DataFrame (df_encoded_standard):
|   fuel_CNG |   fuel_Diesel |   fuel_LPG |   fuel_Petrol |   owner_First Owner |   owner_Fourth & Above Owner |   owner_Second Owner |   owner_Test Drive Car |   owner_Third Owner |
|-----------:|--------------:|-----------:|--------------:|--------------------:|-----------------------------:|---------------------:|-----------------------:|--------------------:|
|          0 |             1 |          0 |             0 |                   1 |                            0 |                    0 |                      0 |                   0 |
|          0 |             1 |          0 |             0 |                   1 |                            0 |                    0 |                      0 |                   0 |
|          0 |             0 |          0 |             1 |                   1 |                            0 |                    0 |                      0 |                   0 |
|          0 |  

In [7]:
df_encoded_k1 = pd.get_dummies(df[['fuel', 'owner']], drop_first=True)
print("First 5 rows of the one-hot encoded DataFrame (df_encoded_k1) with K-1 encoding:")
print(df_encoded_k1.head().to_markdown(index=False))

First 5 rows of the one-hot encoded DataFrame (df_encoded_k1) with K-1 encoding:
|   fuel_Diesel |   fuel_LPG |   fuel_Petrol |   owner_Fourth & Above Owner |   owner_Second Owner |   owner_Test Drive Car |   owner_Third Owner |
|--------------:|-----------:|--------------:|-----------------------------:|---------------------:|-----------------------:|--------------------:|
|             1 |          0 |             0 |                            0 |                    0 |                      0 |                   0 |
|             1 |          0 |             0 |                            0 |                    0 |                      0 |                   0 |
|             0 |          0 |             1 |                            0 |                    0 |                      0 |                   0 |
|             1 |          0 |             0 |                            0 |                    0 |                      0 |                   0 |
|             1 |          0 | 

In [8]:
from sklearn.preprocessing import OneHotEncoder

# Instantiate OneHotEncoder with handle_unknown='ignore' and sparse_output=False
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Select the categorical columns to encode
categorical_cols = ['fuel', 'owner']
df_categorical = df[categorical_cols]

# Fit and transform the selected columns
df_encoded_array = ohe.fit_transform(df_categorical)

# Create a new DataFrame from the encoded array with feature names
df_encoded_ohe = pd.DataFrame(df_encoded_array, columns=ohe.get_feature_names_out(categorical_cols))

# Concatenate the new encoded DataFrame with the original df, dropping the original categorical columns
df_encoded_sklearn = pd.concat([df.drop(columns=categorical_cols), df_encoded_ohe], axis=1)

# Display the first 5 rows of df_encoded_sklearn to verify
print("First 5 rows of the DataFrame after One-Hot Encoding with Scikit-learn:")
print(df_encoded_sklearn.head().to_markdown(index=False))

First 5 rows of the DataFrame after One-Hot Encoding with Scikit-learn:
|   Unnamed: 0 | name    |   year |   selling_price |   km_driven | seller_type   | transmission   |   seats |   max_power (in bph) | Mileage Unit   |   Mileage |   Engine (CC) |   fuel_CNG |   fuel_Diesel |   fuel_LPG |   fuel_Petrol |   owner_First Owner |   owner_Fourth & Above Owner |   owner_Second Owner |   owner_Test Drive Car |   owner_Third Owner |
|-------------:|:--------|-------:|----------------:|------------:|:--------------|:---------------|--------:|---------------------:|:---------------|----------:|--------------:|-----------:|--------------:|-----------:|--------------:|--------------------:|-----------------------------:|---------------------:|-----------------------:|--------------------:|
|            0 | Maruti  |   2014 |          450000 |      145500 | Individual    | Manual         |       5 |                74    | kmpl           |     23.4  |          1248 |          0 |             1 | 

In [9]:
import pandas as pd

# 1. Calculate the value counts for the 'name' column
name_counts = df['name'].value_counts()

# 2. Define a threshold for category frequency
threshold = 100 # Example threshold

# 3. Identify the 'name' categories that have counts below this threshold
infrequent_names = name_counts[name_counts < threshold].index

# 4. Create a new column, df['name_encoded'], by copying the 'name' column
df_encoded_top_categories = df.copy()
df_encoded_top_categories['name_encoded'] = df_encoded_top_categories['name']

# 5. Replace the 'name' categories in df['name_encoded'] that are below the threshold with the string 'uncommon'
df_encoded_top_categories.loc[df_encoded_top_categories['name_encoded'].isin(infrequent_names), 'name_encoded'] = 'uncommon'

# 6. Apply pd.get_dummies() to the df['name_encoded'] column to one-hot encode it.
df_name_ohe = pd.get_dummies(df_encoded_top_categories['name_encoded'], prefix='name')

# 7. Concatenate the resulting one-hot encoded DataFrame with the original df,
# dropping the original 'name' column and the temporary 'name_encoded' column to avoid redundancy.
df_encoded_top_categories = pd.concat([
    df.drop(columns=['name']),
    df_name_ohe
], axis=1)

# 8. Print the first 5 rows of the df_encoded_top_categories DataFrame to verify the changes.
print("First 5 rows of the DataFrame after encoding top 'name' categories:")
print(df_encoded_top_categories.head().to_markdown(index=False))

First 5 rows of the DataFrame after encoding top 'name' categories:
|   Unnamed: 0 |   year |   selling_price |   km_driven | fuel   | seller_type   | transmission   | owner       |   seats |   max_power (in bph) | Mileage Unit   |   Mileage |   Engine (CC) | name_Ford   | name_Hyundai   | name_Maruti   | name_Renault   | name_Tata   | name_Volkswagen   | name_uncommon   |
|-------------:|-------:|----------------:|------------:|:-------|:--------------|:---------------|:------------|--------:|---------------------:|:---------------|----------:|--------------:|:------------|:---------------|:--------------|:---------------|:------------|:------------------|:----------------|
|            0 |   2014 |          450000 |      145500 | Diesel | Individual    | Manual         | First Owner |       5 |                74    | kmpl           |     23.4  |          1248 | False       | False          | True          | False          | False       | False             | False           |
|       

# Assignment 2

In [10]:
news_headlines = [
    'Congress set to approve new spending bill',
    'Stock market surges on positive economic news',
    'Local elections see record voter turnout',
    'New technology promises to revolutionize healthcare',
    'Climate change remains a global concern'
]

preprocessed_headlines = []

for headline in news_headlines:
    # Convert to lowercase and split into words
    tokens = headline.lower().split()
    preprocessed_headlines.append(tokens)

print("Preprocessed Headlines:")
print(preprocessed_headlines)

Preprocessed Headlines:
[['congress', 'set', 'to', 'approve', 'new', 'spending', 'bill'], ['stock', 'market', 'surges', 'on', 'positive', 'economic', 'news'], ['local', 'elections', 'see', 'record', 'voter', 'turnout'], ['new', 'technology', 'promises', 'to', 'revolutionize', 'healthcare'], ['climate', 'change', 'remains', 'a', 'global', 'concern']]


In [11]:
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate CountVectorizer with default parameters
vectorizer = CountVectorizer()

# Fit the vectorizer to the original news_headlines list and transform the text data into a Term-Document Matrix
tdm = vectorizer.fit_transform(news_headlines)

# Convert the tdm into a dense NumPy array for easier viewing
tdm_dense = tdm.toarray()

# Get the feature names (vocabulary) from the fitted CountVectorizer
vocabulary = vectorizer.get_feature_names_out()

print("Shape of the Term-Document Matrix (TDM):", tdm_dense.shape)
print("\nFirst 5 rows of the dense TDM:")
print(tdm_dense[:5])
print("\nVocabulary (feature names):", vocabulary)

Shape of the Term-Document Matrix (TDM): (5, 29)

First 5 rows of the dense TDM:
[[1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0]
 [0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]]

Vocabulary (feature names): ['approve' 'bill' 'change' 'climate' 'concern' 'congress' 'economic'
 'elections' 'global' 'healthcare' 'local' 'market' 'new' 'news' 'on'
 'positive' 'promises' 'record' 'remains' 'revolutionize' 'see' 'set'
 'spending' 'stock' 'surges' 'technology' 'to' 'turnout' 'voter']


In [12]:
print("Document Embeddings (tdm_dense):")
print(tdm_dense)

print("\nBasis Vectors (Terms in Vocabulary):")
print(vocabulary)

Document Embeddings (tdm_dense):
[[1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0]
 [0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]]

Basis Vectors (Terms in Vocabulary):
['approve' 'bill' 'change' 'climate' 'concern' 'congress' 'economic'
 'elections' 'global' 'healthcare' 'local' 'market' 'new' 'news' 'on'
 'positive' 'promises' 'record' 'remains' 'revolutionize' 'see' 'set'
 'spending' 'stock' 'surges' 'technology' 'to' 'turnout' 'voter']


In [13]:
print("Word Embeddings (Transpose of TDM):")
print(tdm_dense.T)

print("\nBasis Vectors (Documents/News Headlines):")
print(news_headlines)

Word Embeddings (Transpose of TDM):
[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]

Basis Vectors (Documents/News Headlines):
['Congress set to approve new spending bill', 'Stock market surges on positive economic news', 'Local elections see record voter turnout', 'New technology promises to revolutionize healthcare', 'Climate change remains a global concern']


In [14]:
print("\n--- Example from tdm_dense ---")

# Let's pick the first document (index 0) as an example
document_index = 0
example_document_tf = tdm_dense[document_index]
example_headline = news_headlines[document_index]

print(f"\nDocument: \"{example_headline}\"")
print(f"TF Vector for this document: {example_document_tf}")

# Get the terms that appear in this document (TF > 0)
terms_in_document = []
for i, tf_value in enumerate(example_document_tf):
    if tf_value > 0:
        terms_in_document.append((vocabulary[i], tf_value))

print("\nTerms and their frequencies in this document:")
for term, freq in terms_in_document:
    print(f"- {term}: {freq}")

print("\nIn this example, words like 'approve', 'bill', 'congress', 'new', 'set', 'spending', 'to' are present. Their non-zero counts in the TF vector indicate their relevance to this specific headline.")


--- Example from tdm_dense ---

Document: "Congress set to approve new spending bill"
TF Vector for this document: [1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0]

Terms and their frequencies in this document:
- approve: 1
- bill: 1
- congress: 1
- new: 1
- set: 1
- spending: 1
- to: 1

In this example, words like 'approve', 'bill', 'congress', 'new', 'set', 'spending', 'to' are present. Their non-zero counts in the TF vector indicate their relevance to this specific headline.


# Assignment 3

In [15]:
from sklearn.datasets import fetch_20newsgroups

# 1. Load the 20 Newsgroups dataset
# By default, fetch_20newsgroups downloads the data if not already present.
newsgroups_data = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))

# 2. Access the news articles
all_news_text = newsgroups_data.data

# 3. Print the total number of documents loaded
print(f"Total number of documents loaded: {len(all_news_text)}")

# 4. Print the first 500 characters of the first document
if all_news_text:
    print(f"\nFirst 500 characters of the first document:\n{all_news_text[0][:500]}")
else:
    print("No documents were loaded.")

Total number of documents loaded: 18846

First 500 characters of the first document:


I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a


In [16]:
import nltk
import string

# Download the 'punkt' tokenizer data if not already present
try:
    nltk.data.find('tokenizers/punkt')
    print("'punkt' tokenizer already downloaded.")
except LookupError:
    nltk.download('punkt')
    print("'punkt' tokenizer downloaded.")

# Download the 'punkt_tab' tokenizer data if not already present (required by some NLTK versions/functions)
try:
    nltk.data.find('tokenizers/punkt_tab')
    print("'punkt_tab' tokenizer already downloaded.")
except LookupError:
    nltk.download('punkt_tab')
    print("'punkt_tab' tokenizer downloaded.")

# Download the 'stopwords' corpus if not already present
try:
    nltk.data.find('corpora/stopwords')
    print("'stopwords' corpus already downloaded.")
except LookupError:
    nltk.download('stopwords')
    print("'stopwords' corpus downloaded.")

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/priyakeshri/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


'punkt' tokenizer downloaded.


[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/priyakeshri/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/priyakeshri/nltk_data...


'punkt_tab' tokenizer downloaded.
'stopwords' corpus downloaded.


[nltk_data]   Unzipping corpora/stopwords.zip.


In [17]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

# Get English stopwords
stop_words = set(stopwords.words('english'))

# Define the preprocessing function
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Tokenize the text
    tokens = word_tokenize(text)

    # Remove punctuation and non-alphanumeric tokens
    tokens = [word for word in tokens if word.isalpha()]

    # Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    return tokens

# Apply the preprocessing function to each document
preprocessed_documents = [preprocess_text(doc) for doc in all_news_text]

# Print the first preprocessed document to verify the output
print(f"Original first document:\n{all_news_text[0][:200]}...")
print(f"\nFirst preprocessed document:\n{preprocessed_documents[0]}")

Original first document:


I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However,...

First preprocessed document:
['sure', 'bashers', 'pens', 'fans', 'pretty', 'confused', 'lack', 'kind', 'posts', 'recent', 'pens', 'massacre', 'devils', 'actually', 'bit', 'puzzled', 'bit', 'relieved', 'however', 'going', 'put', 'end', 'relief', 'bit', 'praise', 'pens', 'man', 'killing', 'devils', 'worse', 'thought', 'jagr', 'showed', 'much', 'better', 'regular', 'season', 'stats', 'also', 'lot', 'fo', 'fun', 'watch', 'playoffs', 'bowman', 'let', 'jagr', 'lot', 'fun', 'next', 'couple', 'games', 'since', 'pens', 'going', 'beat', 'pulp', 'jersey', 'anyway', 'disappointed', 'see', 'islanders', 'lose', 'final', 'regular', 'season', 'game', 'pens', 'rule']


In [18]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Convert list of token lists back to list of strings
processed_texts = [" ".join(doc) for doc in preprocessed_documents]

# Instantiate CountVectorizer and create TF matrix
vectorizer_tf = CountVectorizer()
tf_matrix = vectorizer_tf.fit_transform(processed_texts)

# Instantiate TfidfVectorizer and create TF-IDF matrix
vectorizer_tfidf = TfidfVectorizer()
tfidf_matrix = vectorizer_tfidf.fit_transform(processed_texts)

# Print the shape of the matrices
print(f"Shape of TF Matrix: {tf_matrix.shape}")
print(f"Shape of TF-IDF Matrix: {tfidf_matrix.shape}")

Shape of TF Matrix: (18846, 78395)
Shape of TF-IDF Matrix: (18846, 78395)


In [19]:
import numpy as np

# 1. Convert tf_matrix and tfidf_matrix to dense arrays
tf_dense = tf_matrix.toarray()
tfidf_dense = tfidf_matrix.toarray()

# 2. Calculate the mean TF score for each word
average_tf = np.mean(tf_dense, axis=0)

# 3. Calculate the mean TF-IDF score for each word
average_tfidf = np.mean(tfidf_dense, axis=0)

# 4. Retrieve the vocabulary
vocabulary = vectorizer_tf.get_feature_names_out()

# 5. Create a Pandas DataFrame
comparison_df = pd.DataFrame({
    'Word': vocabulary,
    'Average TF': average_tf,
    'Average TF-IDF': average_tfidf
})

# 6. Sort the DataFrame by 'Average TF' in descending order and display the head
print("\nTop words by Average TF:\n")
print(comparison_df.sort_values(by='Average TF', ascending=False).head(10).to_markdown(index=False))

# 7. Sort the DataFrame by 'Average TF-IDF' in descending order and display the head
print("\nTop words by Average TF-IDF:\n")
print(comparison_df.sort_values(by='Average TF-IDF', ascending=False).head(10).to_markdown(index=False))


Top words by Average TF:

| Word   |   Average TF |   Average TF-IDF |
|:-------|-------------:|-----------------:|
| would  |     0.576886 |       0.0190287  |
| one    |     0.538257 |       0.0160548  |
| people |     0.341823 |       0.0112325  |
| like   |     0.340072 |       0.0131139  |
| get    |     0.308554 |       0.0123591  |
| know   |     0.30468  |       0.0129959  |
| also   |     0.296509 |       0.0095127  |
| use    |     0.264618 |       0.00961116 |
| think  |     0.264353 |       0.0109055  |
| could  |     0.247798 |       0.0104058  |

Top words by Average TF-IDF:

| Word   |   Average TF |   Average TF-IDF |
|:-------|-------------:|-----------------:|
| would  |     0.576886 |       0.0190287  |
| one    |     0.538257 |       0.0160548  |
| like   |     0.340072 |       0.0131139  |
| know   |     0.30468  |       0.0129959  |
| get    |     0.308554 |       0.0123591  |
| people |     0.341823 |       0.0112325  |
| think  |     0.264353 |       0.0109055 